[workspace]
members = ["relay-cli"]

[package]
name = "relay"
version = "0.2.0"
description = "Lightweight HTTP client"
edition = "2021"
license = "MIT"
default-run = "relay"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["json", "rustls-tls", "multipart"], default-features = false }
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
tonic = { version = "0.12", features = ["tls", "tls-roots", "gzip"] }
tonic-reflection = "0.12"
prost = "0.14"
prost-types = "0.14"
prost-reflect = { version = "0.16", features = ["serde"] }
bytes = "1"
http = "1"
protox = "0.9.1"
axum = "0.7"
sysinfo = "0.32"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
