// autocomplete for actual HTTP headers only, not query params/gRPC metadata.
// X-Mock-Scenario is Relay's own header, listed first since it's not muscle memory yet
export const COMMON_HTTP_HEADERS: string[] = [
  "X-Mock-Scenario",
  "Authorization",
  "Content-Type",
  "Accept",
  "Accept-Encoding",
  "Accept-Language",
  "Cache-Control",
  "Cookie",
  "User-Agent",
  "X-Requested-With",
  "X-API-Key",
  "X-Forwarded-For",
  "X-CSRF-Token",
  "Origin",
  "Referer",
  "If-None-Match",
  "If-Modified-Since",
  "If-Match",
  "ETag",
  "Content-Length",
  "Content-Disposition",
  "Content-Encoding",
  "Set-Cookie",
  "Location",
  "Retry-After",
  "WWW-Authenticate",
  "Vary",
];
